import requests
from typing import Dict, Any
import datetime
from .base_fetcher import BaseWeatherFetcher
from ..config import settings
import logging

logger = logging.getLogger(__name__)

class GEFSFetcher(BaseWeatherFetcher):
    """
    Ingests Global Ensemble Forecast System (GEFS) generated by NCEP.
    This fetches via the nomads directory periodically.
    """
    def __init__(self):
        super().__init__(target_topic=settings.TOPIC_GEFS_RAW)

    def fetch_data(self) -> list[Dict[str, Any]]:
        """
        Mock implementation fetching standard GEFS JSON outputs.
        For production, this would download GRIB2 files, parse subset coordinates (e.g. Morocco region), 
        and serialize them into uniform JSON blocks before sending to the pipeline.
        """
        logger.info(f"Fetching GEFS data from {settings.NOAA_API_URL}...")
        
        # NOTE: A true GRIB parser (xarray & cfgrib) is heavy, leaving as JSON mocked ingestion format.
        # Ideally, we query NOAA nomads API for metadata over GRIB files, filter bounds, and push.
        current_time = datetime.datetime.now(datetime.timezone.utc).isoformat()
        
        # Simulating data parsing
        mock_gefs_data = [
            {
                "source": "GEFS",
                "region": "Morocco",
                "latitude": 31.7917,
                "longitude": -7.0926,
                "forecast_time": current_time, 
                "metrics": {
                    "temperature_2m": 305.15, # Kelvin
                    "precipitation_surface": 0.0,
                    "wind_speed_10m": 12.5 
                },
                "metadata": {
                    "ensemble_member": 0,
                    "cycle": "06z"
                }
            }
            #... more elements representing spatial grid
        ]
        
        return mock_gefs_data
